name: Docker Image CI

on:
  push:
    branches:
    - master

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build ./sshd/fedora/ -t lucasfabre/sshd-fedora -f ./sshd/fedora/Dockerfile  
    - name: Docker login
      run:  docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
    - name: Tag the docker image
      run:  docker tag lucasfabre/sshd-fedora lucasfabre/sshd-fedora:latest
    - name: Push the docker image
      run:  docker push lucasfabre/sshd-fedora:latest
