name: Build docker image sshd-debian

on:
  push:
    branches:
    - master
  schedule:
  - cron: "0 6 * * *"

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run:  docker build ./sshd/debian/ -t lucasfabre/sshd-debian -f ./sshd/debian/Dockerfile  
    - name: Docker login
      run:  docker login -u "${{secrets.DOCKER_USERNAME}}" -p "${{secrets.DOCKER_PASSWORD}}"
    - name: Tag the docker image
      run:  docker tag lucasfabre/sshd-debian lucasfabre/sshd-debian:latest
    - name: Push the docker image
      run:  docker push lucasfabre/sshd-debian:latest
